nama =    input("Nama                   : ")
nim =     input("NIM                    : ")
paralel = input("Kelas Paralel          : ")
ttl =     input("Tempat/Tanggal Lahir   : ")
alamat =  input("Almat                  : ")
hobi =    input("Hobby                  : ")
hp =      input("No. HP                 : ")